name: Update SSH keys

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      

env:
  SSH_KEY_REPO: https://github.com/hackerspace-ntnu/ssh-keys.git
  LOCAL_SSH_KEYS: ~/.ssh/local_authorized_keys

jobs:
  update-keys:
    name: Update SSH keys
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          key: ${{ secrets.key }}
          username: ${{ inputs.username }}
          script: |
            git clone $SSH_KEY_REPO /tmp/ssh-keys
            . /tmp/ssh-keys/update_ssh_keys.sh
            rm -r /tmp/ssh-keys
