name: duppeditt

on:
  push:
    branches:
      - main
    paths:
      - "keys/duppeditt/**"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-keys.yml
    with:
      environment: duppeditt
    secrets:
      host: ${{ secrets.ssh_host }}
      port: ${{ secrets.ssh_port }}
      key: ${{ secrets.ssh_key }}
      username: ${{ secrets.username }}
