name: gluteus

on:
  push:
    branches:
      - main
    paths:
      - "keys/gluteus/**"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-keys.yml
    with:
      environment: gluteus
    secrets:
      host: ${{ secrets.HOST }}
      port: ${{ secrets.PORT }}
      key: ${{ secrets.KEY }}
      username: ${{ secrets.USERNAME }}
