name: meieri

on:
  push:
    branches:
      - main
    paths:
      - "keys/meieri/**"
  workflow_dispatch:

jobs:
  run-keys-script:
    name: Update
    uses: ./.github/workflows/update-keys.yml
    with:
      environment: meieri
    secrets:
      host: ${{ secrets.HOST }}
      port: ${{ secrets.PORT }}
      key: ${{ secrets.KEY }}
      username: ${{ secrets.USERNAME }}
