name: Update SSH keys

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      username:
        required: true

env:
  SSH_KEY_REPO: https://github.com/hackerspace-ntnu/ssh-keys.git
  LOCAL_SSH_KEYS: ~/.ssh/local_authorized_keys

jobs:
  update-keys:
    name: Update SSH keys
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          key: ${{ secrets.key }}
          username: ${{ secrets.username }}
          script: |
            git clone ${{ env.SSH_KEY_REPO }} /tmp/ssh-keys
            cd /tmp/ssh-keys
            SSH_KEY_REPO=${{ env.SSH_KEY_REPO }} LOCAL_SSH_KEYS=${{ env.LOCAL_SSH_KEYS }} ./update_ssh_keys.sh /tmp/ssh-keys/keys
            rm -r /tmp/ssh-keys
