name: Update all keys

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-dingseboms:
    name: Update authorized_keys on dingseboms
    uses: ./.github/workflows/update-keys.yaml
    with:
      environment: dingseboms
      # counter-intuitive workflow bug. see https://github.com/AllanOricil/workflow-template-bug/blob/master/.github/workflows/workflow-inplementation.yml
      # this will correctly load environment secrets in the update-keys workflow
    secrets:
      host: ${{ secrets.ssh_host }}
      port: ${{ secrets.ssh_port }}
      key: ${{ secrets.ssh_key }}
      username: ${{ secrets.username }}
  update-duppeditt:
    name: Update authorized_keys on duppeditt
    uses: ./.github/workflows/update-keys.yaml
    with:
      environment: duppeditt
    secrets:
      host: ${{ secrets.ssh_host }}
      port: ${{ secrets.ssh_port }}
      key: ${{ secrets.ssh_key }}
      username: ${{ secrets.username }}
  update-frukt:
    name: Update authorized_keys on frukt
    uses: ./.github/workflows/update-keys.yaml
    with:
      environment: frukt
    secrets:
      host: ${{ secrets.ssh_host }}
      port: ${{ secrets.ssh_port }}
      key: ${{ secrets.ssh_key }}
      username: ${{ secrets.username }}
  update-pve:
    name: Update authorized_keys on pve
    uses: ./.github/workflows/update-keys.yaml
    with:
      environment: pve
    secrets:
      host: ${{ secrets.ssh_host }}
      port: ${{ secrets.ssh_port }}
      key: ${{ secrets.ssh_key }}
      username: ${{ secrets.username }}
