name: Update SSH keys

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      host:
        required: true
      port:
        required: true
      key:
        required: true
      username:
        required: true

env:
  SSH_KEY_REPO: https://github.com/hackerspace-ntnu/ssh-keys.git

jobs:
  update-keys:
    name: Update SSH keys
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          key: ${{ secrets.key }}
          username: ${{ secrets.username }}
          script: |
            set -e
            trap 'rm -rf /tmp/ssh-keys' EXIT
            git clone ${{ env.SSH_KEY_REPO }} /tmp/ssh-keys
            cd /tmp/ssh-keys
            touch authorized_keys.tmp
            echo "" >> authorized_keys.tmp
            for f in $(find keys/${{ inputs.environment }} -type f -name "*.pub"); do
              echo "# $(basename $f)" >> authorized_keys.tmp
              cat $f >> authorized_keys.tmp
              echo "" >> authorized_keys.tmp
            done
            cp authorized_keys.tmp $HOME/.ssh/authorized_keys
            chmod 644 $HOME/.ssh/authorized_keys
            rm -r /tmp/ssh-keys
